### ISSUE TITLE
Provide instructions to update native Dewesoft Data Reader Library

### ISSUE THREAD

**Issue by trcmohitmandokhot** [tomnor/dwdat2py#1]
Hi, thanks for the good work on this library. I wanted to let you know that some of this has helped a ton.   
Dewesoft has continued to upgrade their software version and have periodically provided updates to the Dewesoft Data Reader Library online. After some point of time, the dll versions included in your repository does not appear to work on latest dewesoft software versions. 
Was your intent to continue to upgrade these linked "dll" files in your repository as Dewesoft provides updates to the libraries?  
Alternatively if that is too much to maintain, may I suggest that we upgrade your Readme.RST with some more instructions on how best users can perform upgrades. 
What would you suggest?

**Comment by tomnor** [comment]
Thanks for the kind words and letting me know somebody but me is using
this esoteric project.

trcmohitmandokhot ***@***.***> writes:

> Hi, thanks for the good work on this library. I wanted to let you know that some of this has helped a ton.   
> Dewesoft has continued to upgrade their software version and have periodically provided updates to the Dewesoft Data Reader Library online. After some point of time, the dll versions included in your repository does not appear to work on latest dewesoft software versions. 
> Was your intent to continue to upgrade these linked "dll" files in your repository as Dewesoft provides updates to the libraries?  

It still is my intent, yes.

> Alternatively if that is too much to maintain, may I suggest that we upgrade your Readme.RST with some more instructions on how best users can perform upgrades. 
> What would you suggest? 

I used to get notifications from DS but that seems to have stopped for
some reason. Thanks for notifying me here.

To upgrade "manually", one would download the libs from DS and simply
use them to replace the libraries in a directory called `libs` under the
dwdat2py installation directory. For example on my machine it got
installed here: `/usr/local/lib/python3.9/dist-packages/dwdat2py/`.

A note on the archive that you download is that there are several copies
of for example `DWDataReaderLib64.dll`. They should all be the same so
just pick one of them.

I will update the project shortly and make a note in the readme as per
your suggestion.

**Comment by tomnor** [comment]
@trcmohitmandokhot, the libraries are now updated. Would you like to
try and see if it works for you with those libs? The libs now here is
v24, not v25 as available on the dewesoft website. Something was wrong
with v25 and I wait for the next release.

You would need to install from source since I didnt make a release
yet.

Also I wonder if you could provide a small data file that you had that
didn't work. Maybe by an offlist email.

**Comment by trcmohitmandokhot** [comment]
I have to carefully upgrade my own package to test it for the new dlls. I may not get to it soon but have confidence that it will work, because I have used the dll files on a different machine to test them out. You may close this issue. Thank you.
